/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : dmp
 #	author : miyako
 #	2018/02/14
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

#include <QtCore>

#include "diff_match_patch.h"

// --- new theme1
void diff_match_patch(sLONG_PTR *pResult, PackagePtr pParams);
