/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Diff-Match-Patch.h
 #	source generated by 4D Plugin Wizard
 #	Project : Diff Match Patch
 #	author : miyako
 #	2020/09/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DIFF_MATCH_PATCH_H
#define PLUGIN_DIFF_MATCH_PATCH_H

#include "4DPluginAPI.h"
#include <QtCore>
#include "diff_match_patch.h"
#include "C_LONGINT.h"
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#pragma mark -

void diff_match_patch(PA_PluginParameters params);

#endif /* PLUGIN_DIFF_MATCH_PATCH_H */
